const header = document.querySelector(".site-header");
const toggle = document.querySelector(".menu-button");
const nav = document.querySelector(".site-nav");
const form = document.querySelector(".contact-form");
const bookingForm = document.querySelector(".booking-bar");
const status = document.querySelector(".form-status");
const languageSelect = document.querySelector("#language-select");
const whatsappNumber = "94755240716";

const translations = {
  en: {
    "nav.home": "Home",
    "nav.rooms": "Glamping Units",
    "nav.experiences": "Activities",
    "nav.services": "Facilities",
    "nav.dining": "Dining",
    "nav.gallery": "Gallery",
    "nav.about": "About",
    "nav.location": "Location",
    "nav.contact": "Contact",
    "nav.book": "Book Now",
    "nav.menu": "Menu",
    "language.label": "Language",
    "hero.kicker": "Welcome to Green Heaven Eco Resort",
    "hero.title": "Escape Into<br />Nature &amp; Luxury",
    "hero.copy": "A quiet forest escape near Sigiriya, where nature, comfort and thoughtful hospitality come together.",
    "hero.cta": "Book Your Escape",
    "form.name": "ENTER YOUR NAME",
    "form.phone": "ENTER YOUR WHATSAPP NUMBER",
    "form.date": "Date",
    "form.checkin": "Check-in Date",
    "form.checkout": "Check-out Date",
    "form.guests": "Guests",
    "form.persons": "Persons",
    "form.package": "Package",
    "form.airport": "Airport pickup",
    "form.bookWhatsapp": "Book via WhatsApp",
    "form.sendWhatsapp": "Send via WhatsApp",
    "intro.kicker": "Welcome to Green Heaven Eco Resort",
    "intro.title": "Where eco living meets boutique comfort.",
    "intro.copy": "Green Heaven Eco Resort is being shaped as a nature-first forest stay with A-frame architecture, peaceful views, warm hospitality and thoughtful comfort.",
    "intro.cta": "Discover More",
    "intro.nature": "Nature",
    "intro.natureCopy": "Surrounded by lush greenery.",
    "intro.luxury": "Luxury",
    "intro.luxuryCopy": "Premium stays with comfort.",
    "intro.hospitality": "Hospitality",
    "intro.hospitalityCopy": "Warm service from the heart.",
    "rooms.kicker": "Featured Cabanas",
    "rooms.title": "Choose your private nature stay.",
    "rooms.card1.tag": "Best Seller",
    "rooms.card1.title": "Forest A-Frame Stay",
    "rooms.card1.copy": "Warm timber interiors, a king-size bed and wide glass views into nature.",
    "rooms.card2.tag": "Jungle View",
    "rooms.card2.title": "Canopy View Stay",
    "rooms.card2.copy": "A private outdoor sitting area with forest light and quiet morning views.",
    "rooms.card3.tag": "Luxury Escape",
    "rooms.card3.title": "Evening Glow Retreat",
    "rooms.card3.copy": "A romantic outdoor setting with lanterns, tea and a calm night ambience.",
    "room.size": "Room size",
    "room.bed": "Bed type",
    "room.maxGuests": "Max guests",
    "room.amenities": "Amenities",
    "room.sizeForest": "Private A-frame unit",
    "room.sizeCanopy": "Private nature-view unit",
    "room.sizeEvening": "Private evening deck stay",
    "room.kingBed": "King-size bed",
    "room.doubleBed": "Double bed setup",
    "room.maxGuests3": "Up to 3 guests",
    "room.maxGuests4": "Up to 4 guests",
    "room.amenitiesForest": "WiFi, attached bathroom, outdoor sitting area",
    "room.amenitiesCanopy": "WiFi, parking support, airport pickup on request",
    "room.amenitiesEvening": "Photo gallery, dining setup, nature experiences",
    "stay.kicker": "Stay Details",
    "stay.title": "Everything guests need before booking.",
    "stay.packagesTitle": "Packages",
    "stay.packagesCopy": "Choose the stay plan that matches your trip. Final rates and availability are confirmed directly through WhatsApp.",
    "stay.packageCabana": "Private forest stay only.",
    "stay.packageDayout": "Day visit with nature time and arranged meals.",
    "stay.packageBb": "Stay with breakfast included.",
    "stay.packageHb": "Stay with breakfast and dinner.",
    "stay.packageFb": "Stay with breakfast, lunch and dinner.",
    "stay.packageSafari": "Stay plan with arranged safari experience.",
    "stay.packageRate": "Confirm rate via WhatsApp",
    "stay.packageFrom": "From $XX per night",
    "stay.packageCabanaIncludes": "Nature stay, private room and basic facilities",
    "stay.packageDayoutIncludes": "Day access, outdoor dining and nature time",
    "stay.packageBbIncludes": "Overnight stay with breakfast",
    "stay.packageHbIncludes": "Overnight stay with breakfast and dinner",
    "stay.packageFbIncludes": "Overnight stay with all main meals",
    "stay.packageSafariIncludes": "Room stay, safari support and trip planning",
    "stay.packageAction": "Request Package",
    "stay.nearbyTitle": "Nearby Places",
    "stay.facilitiesTitle": "Facilities",
    "stay.facilityStay": "Private nature stay",
    "stay.facilityBath": "Attached bathroom",
    "stay.facilityDining": "Outdoor dining arrangement",
    "stay.facilityParking": "Parking support",
    "stay.facilityPickup": "Airport pickup on request",
    "stay.policiesTitle": "Policies",
    "stay.policyReserve": "Advance reservation is required.",
    "stay.policyConfirm": "Package price and availability are confirmed by WhatsApp.",
    "stay.policyNature": "Please respect the natural surroundings.",
    "stay.policyFood": "Meal requests should be shared before arrival.",
    "stay.policyPickup": "Airport pickup must be requested in advance.",
    "experience.kicker": "Experiences",
    "experience.title": "Slow mornings, forest days and glowing nights.",
    "experience.copy": "Enjoy the rhythm of Green Heaven: quiet nature walks, private outdoor moments, local discovery and peaceful evenings in warm timber stays.",
    "services.kicker": "Our Services",
    "services.title": "Experiences we arrange.",
    "services.safari": "Minneriya / Kaudulla Jeep Safari",
    "services.village": "Traditional Village Tours",
    "services.boat": "Scenic Boat Ride Experience",
    "services.bbq": "BBQ Night Experience",
    "services.romantic": "Romantic Dinner Setup",
    "services.birds": "Bird Watching Tours",
    "services.bicycle": "Bicycle Tours Around Nature",
    "services.sunrise": "Sunrise and Sunset Nature Experiences",
    "services.cooking": "Traditional Cooking Class",
    "dining.kicker": "Dining",
    "dining.title": "Fresh tastes in nature.",
    "dining.copy": "Breakfast and dining concepts are inspired by Sri Lankan flavours, tropical fruit, warm tea and relaxed service in nature. Final menus will be released before opening.",
    "gallery.kicker": "Gallery",
    "gallery.title": "Concept visuals inspired by the real cabana.",
    "location.kicker": "Location",
    "location.title": "A hidden paradise near Sigiriya.",
    "location.copy": "Use the map to explore the submitted Green Heaven Eco Resort location. Full arrival instructions will be shared with confirmed opening details.",
    "location.map": "Open in Google Maps",
    "nearby.kicker": "Explore the Region",
    "nearby.title": "Places to Visit Nearby",
    "nearby.intro": "Green Heaven is placed close to Habarana nature, Sigiriya heritage and some of the best wildlife experiences in the cultural triangle.",
    "nearby.card1.title": "Pidurangala Rock - 9.3 km",
    "nearby.card1.copy": "This ancient volcanic hill rises opposite Sigiriya Rock, offering an adventurous climb through forest trails. Reaching the summit rewards guests with spectacular 360-degree panoramic views of the entire Sigiriya valley, especially beautiful at sunrise.",
    "nearby.card2.title": "Sigiriya Temple - 9.67 km",
    "nearby.card2.copy": "A serene historical temple located at the base of the Sigiriya Rock fortress. It offers a peaceful spiritual stop where guests can explore ancient shrine rooms, traditional murals, and quiet temple grounds away from the main tourist crowd.",
    "nearby.card3.title": "Minneriya National Park - 12.12 km",
    "nearby.card3.copy": "A world-famous wildlife sanctuary renowned for 'The Gathering' of wild Asian elephants between August and October. Guided jeep safaris offer up-close views of these gentle giants roaming freely around the reservoir.",
    "nearby.card4.title": "Habarana Lake - 1.19 km",
    "nearby.card4.copy": "A scenic local lake situated just a short walk or bicycle ride from the resort. It is a peaceful haven for bird watching, soft evening walks, and traditional catamaran boat rides surrounded by lush tropical greenery.",
    "nearby.card5.title": "Kaudulla National Park - 22 km",
    "nearby.card5.copy": "An important wildlife sanctuary hosting large herds of elephants, particularly during the dry season. Safaris here offer excellent opportunities to see elephants, peacocks, crocodiles, and deer in their natural forest habitat.",
    "nearby.card6.title": "Dambulla Cave Temple - 23.31 km",
    "nearby.card6.copy": "A UNESCO World Heritage site and the largest, best-preserved cave temple complex in Sri Lanka. It features five major caves filled with over 150 stunning Buddha statues and historic murals dating back to the 1st century BC.",
    "nearby.popular": "Most popular landmarks",
    "nearby.closest": "Closest landmarks",
    "policy.goodToKnow": "Good to know",
    "policy.reservation": "Reservation",
    "policy.checkin": "Check-In / Check-Out",
    "policy.checkinTime": "Check-in: 2:00 PM",
    "policy.checkoutTime": "Check-out: 12:00 PM",
    "feedback.kicker": "Guest Feedback",
    "feedback.title": "Warm words from our guests.",
    "feedback.card1": "Excellent hospitality and a peaceful natural setting.",
    "feedback.card2": "A calm stay with beautiful greenery and friendly service.",
    "feedback.card3": "Comfortable rooms, easy booking and helpful local arrangements.",
    "why.kicker": "Why Choose Us",
    "why.title": "Simple comforts for nature-focused stays.",
    "why.eco": "Eco Friendly",
    "why.wifi": "Free WiFi",
    "why.view": "Nature View",
    "why.restaurant": "Restaurant",
    "why.safari": "Safari Tours",
    "why.parking": "Free Parking",
    "contact.kicker": "Contact",
    "contact.title": "Book direct and get the best opening updates.",
    "contact.copy": "Send your preferred travel date, guest count and questions. This is an opening-interest request until final reservations are released.",
    "footer.bestPrice": "Book direct and get the best price",
    "footer.maps": "Open Google Maps",
    "package.cabana": "CABANA ONLY",
    "package.dayout": "DAYOUT",
    "package.bb": "BED & BREAKFAST",
    "package.hb": "HALF BOARD",
    "package.fb": "FULL BOARD",
    "package.safari": "SAFARI PACKAGE",
    "option.no": "No airport pickup",
    "option.yes": "Airport pickup needed",
    "option.confirm": "Need airport pickup details",
    "placeholder.name": "Full name",
    "placeholder.phone": "WhatsApp number",
    "placeholder.persons": "2",
    "placeholder.personsText": "Persons",
    "placeholder.message": "Special requests",
    "status.opening": "Opening WhatsApp with your formatted booking enquiry.",
    "status.button": "Opening WhatsApp"
  },
  si: {
    "nav.home": "මුල් පිටුව",
    "nav.rooms": "වන නවාතැන්",
    "nav.experiences": "අත්දැකීම්",
    "nav.services": "පහසුකම්",
    "nav.dining": "ආහාර",
    "nav.gallery": "ගැලරිය",
    "nav.about": "අපි ගැන",
    "nav.location": "ස්ථානය",
    "nav.contact": "සම්බන්ධතා",
    "nav.book": "දැන් වෙන්කරන්න",
    "nav.menu": "මෙනුව",
    "language.label": "භාෂාව",
    "hero.kicker": "Green Heaven Eco Resort වෙත සාදරයෙන් පිළිගනිමු",
    "hero.title": "ස්වභාවික නිස්කලංකත්වය<br />සහ සුඛෝපභෝගී සුවපහසුව",
    "hero.copy": "සීගිරිය අසල පිහිටි නිහඬ වන පරිසරයක, ස්වභාවය, සුවපහසුව සහ උණුසුම් ආගන්තුක සත්කාර එකට එක්වන නවාතැනක්.",
    "hero.cta": "ඔබේ නවාතැන වෙන්කරන්න",
    "form.name": "ඔබගේ නම ඇතුලත් කරන්න",
    "form.phone": "ඔබගේ WHATSAPP අංකය ඇතුලත් කරන්න",
    "form.date": "දිනය",
    "form.checkin": "පැමිණෙන දිනය",
    "form.checkout": "පිටවන දිනය",
    "form.guests": "අමුත්තන්",
    "form.persons": "පුද්ගලයින්",
    "form.package": "පැකේජය",
    "form.airport": "ගුවන් තොටුපළෙන් රැගෙන ඒම",
    "form.bookWhatsapp": "WhatsApp හරහා වෙන්කරන්න",
    "form.sendWhatsapp": "WhatsApp හරහා යවන්න",
    "intro.kicker": "Green Heaven Eco Resort",
    "intro.title": "ස්වභාවිකත්වය සහ සුවපහසු නවාතැන් එක්වන තැන.",
    "intro.copy": "Green Heaven Eco Resort ස්වභාවය මුල් කරගත් වන නවාතැනක් ලෙස නිර්මාණය වෙමින් පවතී. විශේෂ ගෘහ නිර්මාණය, වනාන්තර දසුන්, උණුසුම් ආගන්තුක සත්කාර සහ නිහඬ සුවපහසුව මෙහි ප්‍රධාන අත්දැකීමයි.",
    "intro.cta": "තව බලන්න",
    "intro.nature": "ස්වභාවය",
    "intro.natureCopy": "හරිත පරිසරයකින් වටවී ඇත.",
    "intro.luxury": "සුඛෝපභෝගීත්වය",
    "intro.luxuryCopy": "සුවපහසුවෙන් පිරි උසස් නවාතැන්.",
    "intro.hospitality": "ආගන්තුක සත්කාර",
    "intro.hospitalityCopy": "හදවතින්ම ලැබෙන උණුසුම් සේවාව.",
    "rooms.kicker": "විශේෂ නවාතැන්",
    "rooms.title": "ඔබේ පුද්ගලික ස්වභාවික නවාතැන තෝරන්න.",
    "rooms.card1.tag": "ජනප්‍රියම",
    "rooms.card1.title": "වන A-Frame නවාතැන් කුටිය",
    "rooms.card1.copy": "උණුසුම් ලී අභ්‍යන්තරය, විශාල සුවපහසු ඇඳක් සහ ස්වභාවය දෙසට විවෘත වන විශාල වීදුරු දසුන්.",
    "rooms.card2.tag": "වනාන්තර දසුන්",
    "rooms.card2.title": "වන දසුන් නවාතැන් කුටිය",
    "rooms.card2.copy": "පෞද්ගලික පිටත ඉඳුම් තැනක්, වනාන්තර ආලෝකය සහ නිහඬ උදෑසන දසුන්.",
    "rooms.card3.tag": "සුඛෝපභෝගී විවේකය",
    "rooms.card3.title": "Evening Glow Retreat",
    "rooms.card3.copy": "මෘදු ආලෝකය, තේ සහ නිස්කලංක වාතාවරණයක් සමග ආදරණීය පිටත ඉඳුම් සැකසුම.",
    "room.size": "කාමර විස්තරය",
    "room.bed": "ඇඳ වර්ගය",
    "room.maxGuests": "උපරිම අමුත්තන්",
    "room.amenities": "පහසුකම්",
    "room.sizeForest": "පෞද්ගලික A-Frame නවාතැන් කුටිය",
    "room.sizeCanopy": "ස්වභාවික දසුන් සහිත පෞද්ගලික නවාතැන් කුටිය",
    "room.sizeEvening": "සන්ධ්‍යා පිටත ඉඳුම් තැනක් සහිත පෞද්ගලික නවාතැන",
    "room.kingBed": "විශාල සුවපහසු ඇඳ",
    "room.doubleBed": "දෙදෙනෙකුට ගැළපෙන ඇඳ සැකසුම",
    "room.maxGuests3": "අමුත්තන් 3 දක්වා",
    "room.maxGuests4": "අමුත්තන් 4 දක්වා",
    "room.amenitiesForest": "WiFi, සම්බන්ධිත නාන කාමරය සහ පිටත ඉඳුම් තැන",
    "room.amenitiesCanopy": "WiFi, වාහන නැවැත්වීමේ සහාය සහ ඉල්ලීම අනුව ගුවන් තොටුපළෙන් රැගෙන ඒම",
    "room.amenitiesEvening": "ඡායාරූප ගැලරිය, ආහාර සැකසුම සහ ස්වභාවික අත්දැකීම්",
    "stay.kicker": "නවාතැන් විස්තර",
    "stay.title": "වෙන්කිරීමට පෙර අමුත්තන් දැනගත යුතු දේ.",
    "stay.packagesTitle": "පැකේජ",
    "stay.packagesCopy": "ඔබගේ ගමනට ගැළපෙන නවාතැන් සැලසුම තෝරන්න. අවසාන මිල සහ ලබාගත හැකි බව WhatsApp හරහා තහවුරු කරනු ලැබේ.",
    "stay.packageCabana": "පෞද්ගලික වන නවාතැන පමණි.",
    "stay.packageDayout": "ස්වභාවික පරිසරයේ දිවා විවේකය සහ සකස් කළ ආහාර.",
    "stay.packageBb": "උදෑසන ආහාරය සමග නවාතැන්.",
    "stay.packageHb": "උදෑසන ආහාරය සහ රාත්‍රී ආහාරය සමග නවාතැන්.",
    "stay.packageFb": "උදෑසන, දවල් සහ රාත්‍රී ආහාර සමග නවාතැන්.",
    "stay.packageSafari": "සංවිධානය කරන සෆාරි අත්දැකීමක් සමග නවාතැන් සැලසුම.",
    "stay.packageRate": "මිල WhatsApp හරහා තහවුරු කරන්න",
    "stay.packageFrom": "රාත්‍රියකට $XX සිට",
    "stay.packageCabanaIncludes": "ස්වභාවික නවාතැන, පෞද්ගලික කාමරය සහ මූලික පහසුකම්",
    "stay.packageDayoutIncludes": "දිවා ප්‍රවේශය, පිටත ආහාර සැකසුම සහ ස්වභාවික විවේකය",
    "stay.packageBbIncludes": "උදෑසන ආහාරය සමග රාත්‍රී නවාතැන්",
    "stay.packageHbIncludes": "උදෑසන ආහාරය සහ රාත්‍රී ආහාරය සමග රාත්‍රී නවාතැන්",
    "stay.packageFbIncludes": "ප්‍රධාන ආහාර සියල්ල සමග රාත්‍රී නවාතැන්",
    "stay.packageSafariIncludes": "නවාතැන්, සෆාරි සහාය සහ ගමන් සැලසුම් කිරීම",
    "stay.packageAction": "පැකේජය විමසන්න",
    "stay.nearbyTitle": "අසල ස්ථාන",
    "stay.facilitiesTitle": "පහසුකම්",
    "stay.facilityStay": "පෞද්ගලික ස්වභාවික නවාතැන",
    "stay.facilityBath": "සම්බන්ධිත නාන කාමරය",
    "stay.facilityDining": "පිටත ආහාර සැකසුම",
    "stay.facilityParking": "වාහන නැවැත්වීමේ සහාය",
    "stay.facilityPickup": "ඉල්ලීම අනුව ගුවන් තොටුපළෙන් රැගෙන ඒම",
    "stay.policiesTitle": "ප්‍රතිපත්ති",
    "stay.policyReserve": "කලින් වෙන්කිරීම අවශ්‍ය වේ.",
    "stay.policyConfirm": "පැකේජ මිල සහ ලබාගත හැකි බව WhatsApp හරහා තහවුරු කරනු ලැබේ.",
    "stay.policyNature": "ස්වභාවික පරිසරයට ගරු කරන්න.",
    "stay.policyFood": "ආහාර ඉල්ලීම් පැමිණීමට පෙර දැනුම් දෙන්න.",
    "stay.policyPickup": "ගුවන් තොටුපළෙන් රැගෙන ඒම කලින් ඉල්ලා සිටිය යුතුය.",
    "experience.kicker": "අත්දැකීම්",
    "experience.title": "නිහඬ උදෑසන, වනාන්තරයේ ගතවන දින සහ ආලෝකවත් රාත්‍රීන්.",
    "experience.copy": "ස්වභාවික ඇවිදීම්, පෞද්ගලික පිටත ඉඳුම් මොහොතවල්, ප්‍රදේශීය සොයාබැලීම් සහ උණුසුම් ලී නවාතැන් තුළ ගතවන නිස්කලංක සන්ධ්‍යා භුක්තිවිඳින්න.",
    "services.kicker": "අපගේ සේවා",
    "services.title": "අපි සැලසුම් කර දෙන අත්දැකීම්.",
    "services.safari": "මින්නේරිය / කවුඩුල්ල ජීප් සෆාරි",
    "services.village": "සාම්ප්‍රදායික ගම්මාන චාරිකා",
    "services.boat": "සුන්දර බෝට්ටු සවාරි අත්දැකීම",
    "services.bbq": "බාබිකියු රාත්‍රී ආහාර අත්දැකීම",
    "services.romantic": "ආදරණීය රාත්‍රී ආහාර සැකසුම",
    "services.birds": "කුරුළු නිරීක්ෂණ චාරිකා",
    "services.bicycle": "ස්වභාවය වටා බයිසිකල් චාරිකා",
    "services.sunrise": "ඉර උදාව සහ ඉර බැසීමේ ස්වභාවික අත්දැකීම්",
    "services.cooking": "සාම්ප්‍රදායික ආහාර පිසීමේ පන්තිය",
    "dining.kicker": "ආහාර",
    "dining.title": "ස්වභාවය මැද නැවුම් රස.",
    "dining.copy": "ශ්‍රී ලාංකික රස, නිවර්තන පලතුරු, උණුසුම් තේ සහ ස්වභාවය තුළ සන්සුන් සේවාව ආහාර අත්දැකීම් සඳහා ආභාෂය වේ.",
    "gallery.kicker": "ගැලරිය",
    "gallery.title": "සැබෑ වන නවාතැන් හැඟීමෙන් ආභාෂය ලැබූ සංකල්ප දසුන්.",
    "location.kicker": "ස්ථානය",
    "location.title": "සීගිරිය අසල සැඟවුණු පාරාදීසයක්.",
    "location.copy": "Green Heaven Eco Resort ස්ථානය ගවේෂණය කිරීමට සිතියම භාවිතා කරන්න. තහවුරු කළ වෙන්කිරීම් සමග පැමිණීමේ සම්පූර්ණ උපදෙස් ලබා දෙන්නෙමු.",
    "location.map": "Google Maps විවෘත කරන්න",
    "nearby.kicker": "ප්‍රදේශය ගවේෂණය කරන්න",
    "nearby.title": "අසල සංචාරය කළ හැකි ස්ථාන",
    "nearby.intro": "Green Heaven, හබරණ ස්වභාවික පරිසරය, සීගිරිය උරුමය සහ සංස්කෘතික ත්‍රිකෝණයේ ප්‍රසිද්ධ වනජීවී අත්දැකීම් අසල පිහිටා ඇත.",
    "nearby.card1.title": "පිදුරංගල පර්වතය - කි.මී. 9.3",
    "nearby.card1.copy": "සීගිරිය පර්වතයට මුහුණලා පිහිටි මෙම ඓතිහාසික කඳු මුදුන නැගීම තරමක් වික්‍රමාන්විත අත්දැකීමකි. කඳු මුදුනට ළඟා වූ විට මුළු සීගිරි නිම්නයම අංශක 360ක කෝණයකින් දර්ශනය වන අතර, එය හිරු උදාව හෝ බැසීම නැරඹීමට කදිම ස්ථානයකි.",
    "nearby.card2.title": "සීගිරිය පන්සල - කි.මී. 9.67",
    "nearby.card2.copy": "සීගිරිය පර්වත පාමුල පිහිටි මෙම පෞරාණික බෞද්ධ විහාරස්ථානය සංචාරකයින්ට සන්සුන් ආධ්‍යාත්මික අත්දැකීමක් ලබා දෙයි. පැරණි පිළිම ගෙවල්, සාම්ප්‍රදායික බිතුසිතුවම් සහ නිස්කලංක වටපිටාව ගවේෂණය කිරීමට මෙය කදිම ස්ථානයකි.",
    "nearby.card3.title": "මින්නේරිය ජාතික උද්‍යානය - කි.මී. 12.12",
    "nearby.card3.copy": "අගෝස්තු සිට ඔක්තෝබර් දක්වා කාලය තුළ ලොව විශාලතම ආසියානු අලි එකතුවන 'The Gathering' අත්දැකීම සඳහා ප්‍රසිද්ධ වනජීවී ගමනාන්තයකි. මින්නේරිය වැව ආශ්‍රිතව අලි ඇතුන්, කොටි, වලසුන් සහ පක්ෂීන් රැසක් දැකගත හැක.",
    "nearby.card4.title": "හබරණ වැව - කි.මී. 1.19",
    "nearby.card4.copy": "නවාතැනේ සිට ඉතා ආසන්නයෙන් පිහිටි මෙම සුන්දර වැව කුරුල්ලන් නැරඹීම, සවස් කාලයේ සැහැල්ලුවෙන් ඇවිදීම සහ ඔරු පැදීම සඳහා කදිම ස්ථානයකි. නිවර්තන වනාන්තරයෙන් වටවූ මෙහි ඉතා සන්සුන් පරිසරයක් ඇත.",
    "nearby.card5.title": "කවුඩුල්ල ජාතික උද්‍යානය - කි.මී. 22",
    "nearby.card5.copy": "වියළි කාලයේදී විශාල අලි රංචු දැකගත හැකි ප්‍රධාන වනජීවී කලාපයකි. වැව වටා පිහිටි තණබිම් සහ වනාන්තරය තුළ ජීප් රථ මගින් ගමන් කරමින් අලි ඇතුන්, මොණරුන් සහ මුවන් නිදහසේ සැරිසරන අයුරු දැකගත හැක.",
    "nearby.card6.title": "දඹුල්ල ගුහා විහාරය - කි.මී. 23.31",
    "nearby.card6.copy": "UNESCO ලෝක උරුමයක් වන මෙය ශ්‍රී ලංකාවේ විශාලතම සහ හොඳින්ම සුරැකි ලෙන් විහාර සංකීර්ණයයි. ක්‍රි.පූ. 1 වන සියවස දක්වා දිවෙන මෙම විහාරය තුළ බුද්ධ ප්‍රතිමා 150කට අධික සංඛ්‍යාවක් සහ පැරණි බිතුසිතුවම් දැකගත හැක.",
    "nearby.popular": "ජනප්‍රියම ස්ථාන",
    "nearby.closest": "ලඟම ස්ථාන",
    "policy.goodToKnow": "දැනගත යුතු කරුණු",
    "policy.reservation": "වෙන්කිරීම",
    "policy.checkin": "පැමිණීම / පිටවීම",
    "policy.checkinTime": "පැමිණීම: ප.ව. 2:00",
    "policy.checkoutTime": "පිටවීම: දහවල් 12:00",
    "feedback.kicker": "අමුත්තන්ගේ අදහස්",
    "feedback.title": "අපගේ අමුත්තන්ගෙන් උණුසුම් අදහස්.",
    "feedback.card1": "විශිෂ්ට ආගන්තුක සත්කාරයක් සහ නිහඬ ස්වභාවික පරිසරයක්.",
    "feedback.card2": "සුන්දර හරිත පරිසරය සහ මිත්‍රශීලී සේවාව සමග සන්සුන් නවාතැනක්.",
    "feedback.card3": "සුවපහසු කාමර, පහසු වෙන්කිරීම සහ ප්‍රයෝජනවත් ප්‍රදේශීය සැලසුම්.",
    "why.kicker": "අපව තෝරාගැනීමට හේතු",
    "why.title": "ස්වභාවය මුල් කරගත් නවාතැන් සඳහා සරල සුවපහසුකම්.",
    "why.eco": "පරිසර හිතකාමී",
    "why.wifi": "නොමිලේ WiFi",
    "why.view": "ස්වභාවික දසුන්",
    "why.restaurant": "ආපනශාලාව",
    "why.safari": "සෆාරි චාරිකා",
    "why.parking": "නොමිලේ වාහන නැවැත්වීම",
    "contact.kicker": "සම්බන්ධතා",
    "contact.title": "සෘජුව වෙන්කර නවතම තොරතුරු ලබාගන්න.",
    "contact.copy": "ඔබගේ කැමති දිනය, පුද්ගලයින් ගණන සහ විශේෂ ඉල්ලීම් අප වෙත එවන්න.",
    "footer.bestPrice": "සෘජුව වෙන්කර හොඳම මිල ලබාගන්න",
    "footer.maps": "Google Maps විවෘත කරන්න",
    "package.cabana": "CABANA ONLY",
    "package.dayout": "DAYOUT",
    "package.bb": "ඇඳ සහ උදේ ආහාරය (B&B)",
    "package.hb": "උදේ සහ රාත්‍රී ආහාරය (HB)",
    "package.fb": "ප්‍රධාන ආහාර වේල් තුනම (FB)",
    "package.safari": "SAFARI PACKAGE",
    "option.no": "ගුවන් තොටුපළෙන් රැගෙන ඒම අවශ්‍ය නැත",
    "option.yes": "ගුවන් තොටුපළෙන් රැගෙන ඒම අවශ්‍යයි",
    "option.confirm": "ගුවන් තොටුපළෙන් රැගෙන ඒමේ විස්තර අවශ්‍යයි",
    "placeholder.name": "සම්පූර්ණ නම",
    "placeholder.phone": "WhatsApp අංකය",
    "placeholder.persons": "2",
    "placeholder.personsText": "පුද්ගලයින්",
    "placeholder.message": "විශේෂ ඉල්ලීම්",
    "status.opening": "ඔබගේ වෙන්කිරීමේ විස්තර සමග WhatsApp විවෘත වෙමින් පවතී.",
    "status.button": "WhatsApp විවෘත වෙමින්"
  },
  fr: {
    "nav.home": "Accueil",
    "nav.rooms": "Unités glamping",
    "nav.experiences": "Activités",
    "nav.services": "Équipements",
    "nav.dining": "Table",
    "nav.gallery": "Galerie",
    "nav.about": "À propos",
    "nav.location": "Lieu",
    "nav.contact": "Contact",
    "nav.book": "Réserver",
    "nav.menu": "Menu",
    "language.label": "Langue",
    "hero.kicker": "Bienvenue au Green Heaven Eco Resort",
    "hero.title": "Évasion nature<br />et confort raffiné",
    "hero.copy": "Un refuge paisible près de Sigiriya, imaginé autour de cabanes en forêt, d’une lumière chaleureuse et de séjours tout en calme.",
    "hero.cta": "Réserver votre séjour",
    "form.name": "ENTREZ VOTRE NOM",
    "form.phone": "ENTREZ VOTRE NUMÉRO WHATSAPP",
    "form.date": "Date",
    "form.checkin": "Date d’arrivée",
    "form.checkout": "Date de départ",
    "form.guests": "Voyageurs",
    "form.persons": "Personnes",
    "form.package": "Forfait",
    "form.airport": "Transfert aéroport",
    "form.bookWhatsapp": "Réserver via WhatsApp",
    "form.sendWhatsapp": "Envoyer via WhatsApp",
    "intro.kicker": "Green Heaven Eco Resort",
    "intro.title": "L’esprit éco rencontre le confort boutique.",
    "intro.copy": "Green Heaven Eco Resort se dessine comme une escapade en cabane pensée d’abord pour la nature, avec une architecture A-frame, des vues sur la forêt, une hospitalité chaleureuse et un luxe paisible.",
    "intro.cta": "Découvrir",
    "intro.nature": "Nature",
    "intro.natureCopy": "Entouré d’une végétation luxuriante.",
    "intro.luxury": "Confort",
    "intro.luxuryCopy": "Des séjours haut de gamme, pensés pour se détendre.",
    "intro.hospitality": "Hospitalité",
    "intro.hospitalityCopy": "Un accueil chaleureux et attentionné.",
    "rooms.kicker": "Cabanes à découvrir",
    "rooms.title": "Choisissez votre séjour privé en pleine nature.",
    "rooms.card1.tag": "Très demandé",
    "rooms.card1.title": "Cabane Forest A-Frame",
    "rooms.card1.copy": "Intérieurs chaleureux en bois, lit king-size et grandes ouvertures vitrées sur la nature.",
    "rooms.card2.tag": "Vue forêt",
    "rooms.card2.title": "Cabane vue canopée",
    "rooms.card2.copy": "Espace extérieur privé, lumière de la forêt et vues paisibles au réveil.",
    "rooms.card3.tag": "Escapade élégante",
    "rooms.card3.title": "Retraite Evening Glow",
    "rooms.card3.copy": "Une terrasse romantique, une ambiance douce, du thé et des soirées apaisantes.",
    "room.size": "Taille de la chambre",
    "room.bed": "Type de lit",
    "room.maxGuests": "Voyageurs max.",
    "room.amenities": "Équipements",
    "room.sizeForest": "Unité A-frame privée",
    "room.sizeCanopy": "Unité privée avec vue nature",
    "room.sizeEvening": "Séjour privé avec terrasse du soir",
    "room.kingBed": "Lit king-size",
    "room.doubleBed": "Configuration lit double",
    "room.maxGuests3": "Jusqu’à 3 voyageurs",
    "room.maxGuests4": "Jusqu’à 4 voyageurs",
    "room.amenitiesForest": "WiFi, salle de bain attenante, espace extérieur",
    "room.amenitiesCanopy": "WiFi, aide au stationnement, transfert aéroport sur demande",
    "room.amenitiesEvening": "Galerie photo, repas préparé, expériences nature",
    "stay.kicker": "Détails du séjour",
    "stay.title": "L’essentiel à savoir avant de réserver.",
    "stay.packagesTitle": "Forfaits",
    "stay.packagesCopy": "Choisissez la formule qui correspond à votre séjour. Les tarifs finaux et la disponibilité sont confirmés directement via WhatsApp.",
    "stay.packageCabana": "Séjour privé en forêt uniquement.",
    "stay.packageDayout": "Visite à la journée avec temps nature et repas organisés.",
    "stay.packageBb": "Séjour avec petit-déjeuner inclus.",
    "stay.packageHb": "Séjour avec petit-déjeuner et dîner.",
    "stay.packageFb": "Séjour avec petit-déjeuner, déjeuner et dîner.",
    "stay.packageSafari": "Formule séjour avec expérience safari organisée.",
    "stay.packageRate": "Tarif à confirmer via WhatsApp",
    "stay.packageFrom": "À partir de $XX par nuit",
    "stay.packageCabanaIncludes": "Séjour nature, chambre privée et équipements essentiels",
    "stay.packageDayoutIncludes": "Accès journée, repas en extérieur et temps nature",
    "stay.packageBbIncludes": "Nuitée avec petit-déjeuner",
    "stay.packageHbIncludes": "Nuitée avec petit-déjeuner et dîner",
    "stay.packageFbIncludes": "Nuitée avec les trois repas principaux",
    "stay.packageSafariIncludes": "Séjour, aide safari et planification du trajet",
    "stay.packageAction": "Demander ce forfait",
    "stay.nearbyTitle": "Lieux à proximité",
    "stay.facilitiesTitle": "Équipements",
    "stay.facilityStay": "Séjour privé en pleine nature",
    "stay.facilityBath": "Salle de bain attenante",
    "stay.facilityDining": "Repas en extérieur sur demande",
    "stay.facilityParking": "Aide au stationnement",
    "stay.facilityPickup": "Transfert aéroport sur demande",
    "stay.policiesTitle": "Conditions",
    "stay.policyReserve": "La réservation à l’avance est nécessaire.",
    "stay.policyConfirm": "Le prix du forfait et la disponibilité sont confirmés via WhatsApp.",
    "stay.policyNature": "Merci de respecter l’environnement naturel.",
    "stay.policyFood": "Les demandes de repas doivent être partagées avant l’arrivée.",
    "stay.policyPickup": "Le transfert aéroport doit être demandé à l’avance.",
    "experience.kicker": "Expériences",
    "experience.title": "Matins lents, journées en forêt et nuits lumineuses.",
    "experience.copy": "Profitez du rythme de Green Heaven : promenades nature, moments privés sur la terrasse, découvertes locales et soirées tranquilles dans des cabanes en bois chaleureux.",
    "services.kicker": "Nos services",
    "services.title": "Expériences que nous organisons.",
    "services.safari": "Safari en jeep à Minneriya / Kaudulla",
    "services.village": "Visites de villages traditionnels",
    "services.boat": "Balade panoramique en bateau",
    "services.bbq": "Soirée barbecue",
    "services.romantic": "Dîner romantique préparé sur demande",
    "services.birds": "Sorties d’observation des oiseaux",
    "services.bicycle": "Balades à vélo au cœur de la nature",
    "services.sunrise": "Expériences nature au lever et au coucher du soleil",
    "services.cooking": "Cours de cuisine traditionnelle",
    "dining.kicker": "Table",
    "dining.title": "Des saveurs fraîches sur la terrasse.",
    "dining.copy": "Les concepts de repas s’inspirent des saveurs sri-lankaises, des fruits tropicaux, du thé chaud et d’un service détendu au cœur de la nature.",
    "gallery.kicker": "Galerie",
    "gallery.title": "Visuels conceptuels inspirés de la vraie cabane.",
    "location.kicker": "Lieu",
    "location.title": "Un paradis discret près de Sigiriya.",
    "location.copy": "Utilisez la carte pour explorer l’emplacement de Green Heaven Eco Resort. Les instructions d’arrivée complètes seront partagées avec les détails de réservation confirmés.",
    "location.map": "Ouvrir Google Maps",
    "nearby.kicker": "Explorer la région",
    "nearby.title": "Lieux à visiter à proximité",
    "nearby.intro": "Green Heaven se trouve près de la nature de Habarana, du patrimoine de Sigiriya et de belles expériences animalières du triangle culturel.",
    "nearby.card1.title": "Pidurangala Rock - 9,3 km",
    "nearby.card1.copy": "Cette colline volcanique s'élève face au rocher de Sigiriya, offrant une ascension aventureuse à travers la forêt. Le sommet récompense les visiteurs par une vue panoramique spectaculaire à 360 degrés sur toute la vallée de Sigiriya, particulièrement magnifique au lever du soleil.",
    "nearby.card2.title": "Temple de Sigiriya - 9,67 km",
    "nearby.card2.copy": "Un sanctuaire bouddhiste historique et serein situé au pied du rocher de Sigiriya. Il offre une halte spirituelle paisible pour explorer des salles de sanctuaire anciennes, des peintures traditionnelles et des jardins calmes à l'écart des foules.",
    "nearby.card3.title": "Parc national de Minneriya - 12,12 km",
    "nearby.card3.copy": "Un sanctuaire de réputation mondiale célèbre pour le grand rassemblement d'éléphants sauvages ('The Gathering') d'août à octobre. Les safaris guidés en jeep permettent d'observer de près ces créatures fascinantes en liberté autour du réservoir.",
    "nearby.card4.title": "Lac de Habarana - 1,19 km",
    "nearby.card4.copy": "Un lac naturel pittoresque situé à seulement quelques minutes à pied ou à vélo du resort. C'est un véritable havre de paix idéal pour l'observation des oiseaux, les promenades tranquilles en soirée et les tours en bateau traditionnel.",
    "nearby.card5.title": "Parc national de Kaudulla - 22 km",
    "nearby.card5.copy": "Une réserve naturelle de zone sèche et un corridor migratoire essentiel qui accueille de grands troupeaux d'éléphants. Le safari guidé offre d'excellentes occasions de voir des éléphants, des paons, des crocodiles et des cerfs dans leur habitat naturel.",
    "nearby.card6.title": "Temple rupestre de Dambulla - 23,31 km",
    "nearby.card6.copy": "Un site classé au patrimoine mondial de l'UNESCO et le temple rupestre le plus grand et le mieux préservé du Sri Lanka. Il comprend cinq grandes grottes abritant plus de 150 magnifiques statues de Bouddha et des fresques historiques.",
    "nearby.popular": "Sites les plus populaires",
    "nearby.closest": "Sites les plus proches",
    "policy.goodToKnow": "Bon à savoir",
    "policy.reservation": "Réservation",
    "policy.checkin": "Arrivée / Départ",
    "policy.checkinTime": "Arrivée : 14 h 00",
    "policy.checkoutTime": "Départ : 12 h 00",
    "feedback.kicker": "Avis des voyageurs",
    "feedback.title": "Quelques mots chaleureux de nos voyageurs.",
    "feedback.card1": "Excellente hospitalité et cadre naturel paisible.",
    "feedback.card2": "Un séjour calme avec une belle verdure et un service attentionné.",
    "feedback.card3": "Chambres confortables, réservation facile et aide locale utile.",
    "why.kicker": "Pourquoi nous choisir",
    "why.title": "Des conforts simples pour des séjours proches de la nature.",
    "why.eco": "Éco-responsable",
    "why.wifi": "WiFi gratuit",
    "why.view": "Vue nature",
    "why.restaurant": "Restaurant",
    "why.safari": "Safaris",
    "why.parking": "Parking gratuit",
    "contact.kicker": "Contact",
    "contact.title": "Réservez en direct et recevez les meilleures informations.",
    "contact.copy": "Envoyez votre date préférée, le nombre de personnes et vos demandes particulières.",
    "footer.bestPrice": "Réservez en direct et obtenez le meilleur prix",
    "footer.maps": "Ouvrir Google Maps",
    "package.cabana": "CABANA ONLY",
    "package.dayout": "DAYOUT",
    "package.bb": "CHAMBRE & PETIT-DÉJEUNER",
    "package.hb": "DEMI-PENSION",
    "package.fb": "PENSION COMPLÈTE",
    "package.safari": "SAFARI PACKAGE",
    "option.no": "Pas de transfert aéroport",
    "option.yes": "Transfert aéroport souhaité",
    "option.confirm": "Besoin d’informations sur le transfert",
    "placeholder.name": "Nom complet",
    "placeholder.phone": "Numéro WhatsApp",
    "placeholder.persons": "2",
    "placeholder.personsText": "Personnes",
    "placeholder.message": "Demandes particulières",
    "status.opening": "Ouverture de WhatsApp avec votre demande de réservation.",
    "status.button": "Ouverture de WhatsApp"
  },
  de: {
    "nav.home": "Startseite",
    "nav.rooms": "Glamping-Einheiten",
    "nav.experiences": "Aktivitäten",
    "nav.services": "Ausstattung",
    "nav.dining": "Kulinarik",
    "nav.gallery": "Galerie",
    "nav.about": "Über uns",
    "nav.location": "Lage",
    "nav.contact": "Kontakt",
    "nav.book": "Jetzt buchen",
    "nav.menu": "Menü",
    "language.label": "Sprache",
    "hero.kicker": "Willkommen im Green Heaven Eco Resort",
    "hero.title": "Natur erleben<br />mit stilvollem Komfort",
    "hero.copy": "Ein verstecktes Paradies nahe Sigiriya, gestaltet rund um Wald-Cabanas, warmes Licht und erholsame Aufenthalte.",
    "hero.cta": "Aufenthalt buchen",
    "form.name": "GEBEN SIE IHREN NAMEN EIN",
    "form.phone": "GEBEN SIE IHRE WHATSAPP-NUMMER EIN",
    "form.date": "Datum",
    "form.checkin": "Check-in-Datum",
    "form.checkout": "Check-out-Datum",
    "form.guests": "Gäste",
    "form.persons": "Personen",
    "form.package": "Paket",
    "form.airport": "Flughafentransfer",
    "form.bookWhatsapp": "Über WhatsApp buchen",
    "form.sendWhatsapp": "Über WhatsApp senden",
    "intro.kicker": "Green Heaven Eco Resort",
    "intro.title": "Naturnahes Leben trifft Boutique-Komfort.",
    "intro.copy": "Green Heaven Eco Resort entsteht als naturorientierte Cabana-Auszeit mit A-frame-Architektur, Blick in den Wald, herzlicher Gastfreundschaft und ruhigem Luxus.",
    "intro.cta": "Mehr entdecken",
    "intro.nature": "Natur",
    "intro.natureCopy": "Umgeben von üppigem Grün.",
    "intro.luxury": "Komfort",
    "intro.luxuryCopy": "Hochwertige Aufenthalte mit viel Behaglichkeit.",
    "intro.hospitality": "Gastfreundschaft",
    "intro.hospitalityCopy": "Herzlicher Service mit persönlicher Note.",
    "rooms.kicker": "Ausgewählte Cabanas",
    "rooms.title": "Wählen Sie Ihren privaten Aufenthalt in der Natur.",
    "rooms.card1.tag": "Sehr beliebt",
    "rooms.card1.title": "Forest A-Frame Cabana",
    "rooms.card1.copy": "Warme Holzinterieurs, Kingsize-Bett und Glasfronten mit Blick in die Natur.",
    "rooms.card2.tag": "Waldblick",
    "rooms.card2.title": "Cabana mit Waldblick",
    "rooms.card2.copy": "Privater Außenbereich, sanftes Waldlicht und ruhige Ausblicke am Morgen.",
    "rooms.card3.tag": "Luxus-Auszeit",
    "rooms.card3.title": "Evening Glow Retreat",
    "rooms.card3.copy": "Ein romantischer Außenbereich mit weichem Licht, Tee und entspannter Abendstimmung.",
    "room.size": "Zimmergröße",
    "room.bed": "Betttyp",
    "room.maxGuests": "Max. Gäste",
    "room.amenities": "Ausstattung",
    "room.sizeForest": "Private A-frame-Einheit",
    "room.sizeCanopy": "Private Einheit mit Naturblick",
    "room.sizeEvening": "Privater Aufenthalt mit Abendterrasse",
    "room.kingBed": "Kingsize-Bett",
    "room.doubleBed": "Doppelbett-Setup",
    "room.maxGuests3": "Bis zu 3 Gäste",
    "room.maxGuests4": "Bis zu 4 Gäste",
    "room.amenitiesForest": "WiFi, eigenes Badezimmer, Außenbereich",
    "room.amenitiesCanopy": "WiFi, Parkhilfe, Flughafentransfer auf Anfrage",
    "room.amenitiesEvening": "Fotogalerie, Dinner-Setup, Naturerlebnisse",
    "stay.kicker": "Aufenthaltsdetails",
    "stay.title": "Alles Wichtige vor der Buchung.",
    "stay.packagesTitle": "Pakete",
    "stay.packagesCopy": "Wählen Sie das Paket, das zu Ihrer Reise passt. Endpreise und Verfügbarkeit werden direkt per WhatsApp bestätigt.",
    "stay.packageCabana": "Nur privater Aufenthalt im Wald.",
    "stay.packageDayout": "Tagesbesuch mit Naturzeit und arrangierten Mahlzeiten.",
    "stay.packageBb": "Aufenthalt inklusive Frühstück.",
    "stay.packageHb": "Aufenthalt mit Frühstück und Abendessen.",
    "stay.packageFb": "Aufenthalt mit Frühstück, Mittagessen und Abendessen.",
    "stay.packageSafari": "Aufenthaltspaket mit organisiertem Safari-Erlebnis.",
    "stay.packageRate": "Preis per WhatsApp bestätigen",
    "stay.packageFrom": "Ab $XX pro Nacht",
    "stay.packageCabanaIncludes": "Naturaufenthalt, privates Zimmer und Grundausstattung",
    "stay.packageDayoutIncludes": "Tageszugang, Essen im Freien und Naturzeit",
    "stay.packageBbIncludes": "Übernachtung mit Frühstück",
    "stay.packageHbIncludes": "Übernachtung mit Frühstück und Abendessen",
    "stay.packageFbIncludes": "Übernachtung mit allen Hauptmahlzeiten",
    "stay.packageSafariIncludes": "Zimmeraufenthalt, Safari-Unterstützung und Reiseplanung",
    "stay.packageAction": "Paket anfragen",
    "stay.nearbyTitle": "Orte in der Nähe",
    "stay.facilitiesTitle": "Ausstattung",
    "stay.facilityStay": "Privater Aufenthalt in der Natur",
    "stay.facilityBath": "Eigenes Badezimmer",
    "stay.facilityDining": "Essen im Außenbereich auf Anfrage",
    "stay.facilityParking": "Unterstützung beim Parken",
    "stay.facilityPickup": "Flughafentransfer auf Anfrage",
    "stay.policiesTitle": "Richtlinien",
    "stay.policyReserve": "Eine Reservierung im Voraus ist erforderlich.",
    "stay.policyConfirm": "Paketpreis und Verfügbarkeit werden per WhatsApp bestätigt.",
    "stay.policyNature": "Bitte respektieren Sie die natürliche Umgebung.",
    "stay.policyFood": "Essenswünsche sollten vor der Anreise mitgeteilt werden.",
    "stay.policyPickup": "Der Flughafentransfer muss im Voraus angefragt werden.",
    "experience.kicker": "Erlebnisse",
    "experience.title": "Langsame Morgen, Waldtage und leuchtende Nächte.",
    "experience.copy": "Genießen Sie den Rhythmus von Green Heaven: Spaziergänge in der Natur, private Momente im Freien, lokale Entdeckungen und friedliche Abende in warmen Holz-Cabanas.",
    "services.kicker": "Unsere Angebote",
    "services.title": "Erlebnisse, die wir für Sie organisieren.",
    "services.safari": "Jeep-Safari in Minneriya / Kaudulla",
    "services.village": "Traditionelle Dorftouren",
    "services.boat": "Malerische Bootsfahrt",
    "services.bbq": "BBQ-Abend",
    "services.romantic": "Romantisches Dinner-Setup",
    "services.birds": "Vogelbeobachtungstouren",
    "services.bicycle": "Fahrradtouren durch die Natur",
    "services.sunrise": "Naturerlebnisse bei Sonnenaufgang und Sonnenuntergang",
    "services.cooking": "Traditioneller Kochkurs",
    "dining.kicker": "Kulinarik",
    "dining.title": "Frische Aromen mitten in der Natur.",
    "dining.copy": "Die Dining-Konzepte sind inspiriert von sri-lankischen Aromen, tropischen Früchten, warmem Tee und entspanntem Service mitten in der Natur.",
    "gallery.kicker": "Galerie",
    "gallery.title": "Konzeptbilder, inspiriert von der echten Cabana.",
    "location.kicker": "Lage",
    "location.title": "Ein verstecktes Paradies nahe Sigiriya.",
    "location.copy": "Nutzen Sie die Karte, um die Lage des Green Heaven Eco Resort zu erkunden. Vollständige Anreiseinformationen werden mit den bestätigten Buchungsdetails geteilt.",
    "location.map": "Google Maps öffnen",
    "nearby.kicker": "Die Region erkunden",
    "nearby.title": "Orte in der Nähe",
    "nearby.intro": "Green Heaven liegt nahe der Natur von Habarana, dem Kulturerbe von Sigiriya und starken Wildlife-Erlebnissen im Kulturdreieck.",
    "nearby.card1.title": "Pidurangala Rock - 9,3 km",
    "nearby.card1.copy": "Dieser historische Vulkanhügel erhebt sich direkt gegenüber dem Sigiriya-Felsen und bietet einen abenteuerlichen Aufstieg durch Waldpfade. Der Gipfel belohnt Sie mit einem atemberaubenden 360-Grad-Blick über das gesamte Sigiriya-Tal, besonders schön bei Sonnenaufgang.",
    "nearby.card2.title": "Sigiriya-Tempel - 9,67 km",
    "nearby.card2.copy": "Ein historisches und friedliches buddhistisches Heiligtum am Fuße der Festung Sigiriya. Der Tempelkomplex bietet einen ruhigen, spirituellen Zwischenstopp mit alten Schreinen und ruhigen Wegen abseits der Touristenströme.",
    "nearby.card3.title": "Minneriya-Nationalpark - 12,12 km",
    "nearby.card3.copy": "Ein weltberühmtes Wildschutzgebiet, bekannt für 'The Gathering' – die größte Versammlung wilder asiatischer Elefanten der Erde von August bis Oktober. Geführte Jeep-Safaris bieten unvergessliche Begegnungen mit den Tieren.",
    "nearby.card4.title": "Habarana Lake - 1,19 km",
    "nearby.card4.copy": "Ein malerischer natürlicher See, nur einen kurzen Spaziergang oder eine Radtour vom Resort entfernt. Ein friedlicher Zufluchtsort für Vogelbeobachtungen, entspannte Spaziergänge und traditionelle Bootsfahrten.",
    "nearby.card5.title": "Kaudulla-Nationalpark - 22 km",
    "nearby.card5.copy": "Ein wichtiges Schutzgebiet und Migrationskorridor, in dem sich besonders in der Trockenzeit große Elefantenherden versammeln. Bietet hervorragende Möglichkeiten, Elefanten, Pfaue und Krokodile in freier Wildbahn zu beobachten.",
    "nearby.card6.title": "Dambulla-Höhlentempel - 23,31 km",
    "nearby.card6.copy": "Ein UNESCO-Weltkulturerbe und der größte, am besten erhaltene Höhlentempelkomplex in Sri Lanka mit fünf Höhlen voller beeindruckender Buddha-Statuen und Wandmalereien aus dem 1. Jahrhundert v. Chr.",
    "nearby.popular": "Beliebteste Sehenswürdigkeiten",
    "nearby.closest": "Nächstgelegene Sehenswürdigkeiten",
    "policy.goodToKnow": "Gut zu wissen",
    "policy.reservation": "Reservierung",
    "policy.checkin": "Check-in / Check-out",
    "policy.checkinTime": "Check-in: 14:00 Uhr",
    "policy.checkoutTime": "Check-out: 12:00 Uhr",
    "feedback.kicker": "Gästefeedback",
    "feedback.title": "Warme Worte unserer Gäste.",
    "feedback.card1": "Ausgezeichnete Gastfreundschaft und eine friedliche natürliche Umgebung.",
    "feedback.card2": "Ein ruhiger Aufenthalt mit schöner Natur und freundlichem Service.",
    "feedback.card3": "Komfortable Zimmer, einfache Buchung und hilfreiche lokale Organisation.",
    "why.kicker": "Warum Green Heaven",
    "why.title": "Einfacher Komfort für naturnahe Aufenthalte.",
    "why.eco": "Umweltfreundlich",
    "why.wifi": "Kostenloses WiFi",
    "why.view": "Naturblick",
    "why.restaurant": "Restaurant",
    "why.safari": "Safari-Touren",
    "why.parking": "Kostenloses Parken",
    "contact.kicker": "Kontakt",
    "contact.title": "Direkt buchen und die besten Updates erhalten.",
    "contact.copy": "Senden Sie Ihr Wunschdatum, die Personenzahl und besondere Wünsche.",
    "footer.bestPrice": "Direkt buchen und den besten Preis erhalten",
    "footer.maps": "Google Maps öffnen",
    "package.cabana": "CABANA ONLY",
    "package.dayout": "DAYOUT",
    "package.bb": "ÜBERNACHTUNG MIT FRÜHSTÜCK",
    "package.hb": "HALBPENSION",
    "package.fb": "VOLLPENSION",
    "package.safari": "SAFARI PACKAGE",
    "option.no": "Kein Flughafentransfer",
    "option.yes": "Flughafentransfer gewünscht",
    "option.confirm": "Details zum Flughafentransfer benötigt",
    "placeholder.name": "Vollständiger Name",
    "placeholder.phone": "WhatsApp-Nummer",
    "placeholder.persons": "2",
    "placeholder.personsText": "Personen",
    "placeholder.message": "Besondere Wünsche",
    "status.opening": "WhatsApp wird mit Ihrer Buchungsanfrage geöffnet.",
    "status.button": "WhatsApp wird geöffnet"
  },
  zh: {
    "nav.home": "首页",
    "nav.rooms": "豪华露营房型",
    "nav.experiences": "活动",
    "nav.services": "设施",
    "nav.dining": "餐饮",
    "nav.gallery": "相册",
    "nav.about": "关于我们",
    "nav.location": "位置",
    "nav.contact": "联系",
    "nav.book": "立即预订",
    "nav.menu": "菜单",
    "language.label": "语言",
    "hero.kicker": "欢迎来到 Green Heaven Eco Resort",
    "hero.title": "走进自然<br />享受精致舒适",
    "hero.copy": "位于锡吉里耶附近的隐秘度假地，以森林小屋、温暖灯光和宁静住宿体验为核心打造。",
    "hero.cta": "预订您的假期",
    "form.name": "输入您的姓名",
    "form.phone": "输入您的 WHATSAPP 号码",
    "form.date": "日期",
    "form.checkin": "入住日期",
    "form.checkout": "退房日期",
    "form.guests": "客人人数",
    "form.persons": "人数",
    "form.package": "套餐",
    "form.airport": "机场接送",
    "form.bookWhatsapp": "通过 WhatsApp 预订",
    "form.sendWhatsapp": "通过 WhatsApp 发送",
    "intro.kicker": "Green Heaven Eco Resort",
    "intro.title": "生态生活与精品舒适在此相遇。",
    "intro.copy": "Green Heaven Eco Resort 正在打造以自然为核心的森林小屋度假体验，融合 A-frame 建筑、森林景观、温暖服务与宁静的高级舒适感。",
    "intro.cta": "了解更多",
    "intro.nature": "自然",
    "intro.natureCopy": "被郁郁葱葱的绿意环绕。",
    "intro.luxury": "舒适",
    "intro.luxuryCopy": "兼具品质与放松感的住宿体验。",
    "intro.hospitality": "待客之道",
    "intro.hospitalityCopy": "真诚而温暖的服务。",
    "rooms.kicker": "精选小屋",
    "rooms.title": "选择您的私人自然住宿。",
    "rooms.card1.tag": "热门选择",
    "rooms.card1.title": "Forest A-Frame 小屋",
    "rooms.card1.copy": "温暖木质内饰、特大床，以及透过玻璃欣赏自然景观。",
    "rooms.card2.tag": "森林景观",
    "rooms.card2.title": "林冠景观小屋",
    "rooms.card2.copy": "私人露台、森林光影，以及宁静清晨景色。",
    "rooms.card3.tag": "精致度假",
    "rooms.card3.title": "Evening Glow Retreat",
    "rooms.card3.copy": "浪漫露台布置、柔和灯光、热茶与安静夜晚氛围。",
    "room.size": "房型面积",
    "room.bed": "床型",
    "room.maxGuests": "最多客人",
    "room.amenities": "设施",
    "room.sizeForest": "私人 A-frame 房型",
    "room.sizeCanopy": "私人自然景观房型",
    "room.sizeEvening": "私人夜景露台住宿",
    "room.kingBed": "特大床",
    "room.doubleBed": "双人床布置",
    "room.maxGuests3": "最多 3 位客人",
    "room.maxGuests4": "最多 4 位客人",
    "room.amenitiesForest": "WiFi、独立浴室、户外休息区",
    "room.amenitiesCanopy": "WiFi、停车协助、可按要求安排机场接送",
    "room.amenitiesEvening": "照片展示、用餐布置、自然体验",
    "stay.kicker": "住宿详情",
    "stay.title": "预订前需要了解的信息。",
    "stay.packagesTitle": "套餐",
    "stay.packagesCopy": "请选择适合您行程的住宿方案。最终价格和可订情况将通过 WhatsApp 直接确认。",
    "stay.packageCabana": "仅包含私人森林住宿。",
    "stay.packageDayout": "日间到访，含自然休闲时间及安排餐食。",
    "stay.packageBb": "住宿含早餐。",
    "stay.packageHb": "住宿含早餐和晚餐。",
    "stay.packageFb": "住宿含早餐、午餐和晚餐。",
    "stay.packageSafari": "包含安排野生动物游览体验的住宿方案。",
    "stay.packageRate": "通过 WhatsApp 确认价格",
    "stay.packageFrom": "每晚 $XX 起",
    "stay.packageCabanaIncludes": "自然住宿、私人客房和基础设施",
    "stay.packageDayoutIncludes": "日间使用、户外用餐和自然休闲时间",
    "stay.packageBbIncludes": "含早餐的过夜住宿",
    "stay.packageHbIncludes": "含早餐和晚餐的过夜住宿",
    "stay.packageFbIncludes": "含三顿主餐的过夜住宿",
    "stay.packageSafariIncludes": "客房住宿、游览协助和行程安排",
    "stay.packageAction": "咨询套餐",
    "stay.nearbyTitle": "附近地点",
    "stay.facilitiesTitle": "设施",
    "stay.facilityStay": "私人自然住宿",
    "stay.facilityBath": "独立浴室",
    "stay.facilityDining": "户外用餐安排",
    "stay.facilityParking": "停车协助",
    "stay.facilityPickup": "可按要求安排机场接送",
    "stay.policiesTitle": "政策",
    "stay.policyReserve": "需要提前预订。",
    "stay.policyConfirm": "套餐价格和可订情况将通过 WhatsApp 确认。",
    "stay.policyNature": "请尊重自然环境。",
    "stay.policyFood": "餐食要求请在抵达前告知。",
    "stay.policyPickup": "机场接送需提前提出申请。",
    "experience.kicker": "体验",
    "experience.title": "慢节奏清晨、森林白日与温暖夜晚。",
    "experience.copy": "感受 Green Heaven 的自然节奏：自然漫步、私人露台时光、当地探索，以及木质小屋中的宁静夜晚。",
    "services.kicker": "我们的服务",
    "services.title": "我们可为您安排的体验。",
    "services.safari": "Minneriya / Kaudulla 吉普车野生动物之旅",
    "services.village": "传统村落游览",
    "services.boat": "风景船游体验",
    "services.bbq": "BBQ 夜晚体验",
    "services.romantic": "浪漫晚餐布置",
    "services.birds": "观鸟之旅",
    "services.bicycle": "自然骑行体验",
    "services.sunrise": "日出与日落自然体验",
    "services.cooking": "传统烹饪课程",
    "dining.kicker": "餐饮",
    "dining.title": "露台上的新鲜风味。",
    "dining.copy": "餐饮概念灵感来自斯里兰卡风味、热带水果、热茶，以及自然环境中的轻松服务。",
    "gallery.kicker": "相册",
    "gallery.title": "受真实小屋启发的概念视觉。",
    "location.kicker": "位置",
    "location.title": "锡吉里耶附近的隐秘天堂。",
    "location.copy": "您可以通过地图查看 Green Heaven Eco Resort 的位置。确认预订后，我们将提供完整的到达说明。",
    "location.map": "打开 Google Maps",
    "nearby.kicker": "探索周边地区",
    "nearby.title": "附近值得前往的地点",
    "nearby.intro": "Green Heaven 靠近 Habarana 自然景观、Sigiriya 文化遗产，以及文化三角区内热门的野生动物体验。",
    "nearby.card1.title": "Pidurangala Rock - 9.3 公里",
    "nearby.card1.copy": "这座古老的火山丘陵坐落在锡吉里耶巨石对面，提供穿越森林小径的冒险攀登。登顶后可饱览 360 度的壮丽全景，是观赏日出或日落的最佳地点。",
    "nearby.card2.title": "Sigiriya Temple - 9.67 公里",
    "nearby.card2.copy": "位于锡吉里耶岩石要塞底部的历史佛教圣地。寺庙建筑群提供了一个宁静的精神驿站，游客可以探索古老的佛堂和宁静的花园小径，避开拥挤的人群。",
    "nearby.card3.title": "Minneriya National Park - 12.12 公里",
    "nearby.card3.copy": "世界闻名的野生动物保护区，以 8 月至 10 月期间的“大聚会”（地球上最大规模的野生亚洲象集聚）而闻名。吉普车游猎让您能够近距离接触这些温和的巨兽。",
    "nearby.card4.title": "Habarana Lake - 1.19 公里",
    "nearby.card4.copy": "一个风景如画的自然湖泊，距离度假村仅几步之遥或骑自行车即可到达。是观鸟、傍晚散步和体验传统双体船游览的宁静避风港，被繁茂的绿色所包围。",
    "nearby.card5.title": "Kaudulla National Park - 22 公里",
    "nearby.card5.copy": "一个关键的野生动物保护区，在旱季期间有大量大象聚集。吉普车游猎提供极佳的机会，让您可以在其自然森林栖息地观赏大象、孔雀、鳄鱼和鹿。",
    "nearby.card6.title": "Dambulla Cave Temple - 23.31 公里",
    "nearby.card6.copy": "联合国教科文组织世界遗产，也是斯里兰卡最大、保存最完好的洞穴寺庙群，包含五个主要洞穴，里面有 150 多尊精美的佛像和壁画，历史可追溯至公元前 1 世纪。",
    "nearby.popular": "最受欢迎的地标",
    "nearby.closest": "最近的地标",
    "policy.goodToKnow": "入住须知",
    "policy.reservation": "预订",
    "policy.checkin": "入住 / 退房",
    "policy.checkinTime": "入住：下午 2:00",
    "policy.checkoutTime": "退房：中午 12:00",
    "feedback.kicker": "客人反馈",
    "feedback.title": "来自客人的温暖评价。",
    "feedback.card1": "热情周到的服务，以及宁静的自然环境。",
    "feedback.card2": "一次安静的住宿体验，拥有美丽绿意和友好服务。",
    "feedback.card3": "房间舒适，预订方便，当地行程安排也很贴心。",
    "why.kicker": "为什么选择我们",
    "why.title": "为自然住宿准备的舒适基础体验。",
    "why.eco": "环保友好",
    "why.wifi": "免费 WiFi",
    "why.view": "自然景观",
    "why.restaurant": "餐厅",
    "why.safari": "游猎行程",
    "why.parking": "免费停车",
    "contact.kicker": "联系",
    "contact.title": "直接预订，获取最新优惠与信息。",
    "contact.copy": "请发送您的首选日期、人数以及特别要求。",
    "footer.bestPrice": "直接预订，获得最优价格",
    "footer.maps": "打开 Google Maps",
    "package.cabana": "CABANA ONLY",
    "package.dayout": "DAYOUT",
    "package.bb": "床位与早餐 (B&B)",
    "package.hb": "半食宿 (HB)",
    "package.fb": "全食宿 (FB)",
    "package.safari": "SAFARI PACKAGE",
    "option.no": "不需要机场接送",
    "option.yes": "需要机场接送",
    "option.confirm": "需要机场接送详情",
    "placeholder.name": "全名",
    "placeholder.phone": "WhatsApp 号码",
    "placeholder.persons": "2",
    "placeholder.personsText": "人数",
    "placeholder.message": "特别要求",
    "status.opening": "正在打开 WhatsApp，并带上您的预订咨询内容。",
    "status.button": "正在打开 WhatsApp"
  }
};

const getTranslation = (key, language) => {
  return translations[language]?.[key] || translations.en[key] || "";
};

const applyLanguage = (language) => {
  document.documentElement.lang = language;

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const value = getTranslation(element.dataset.i18n, language);
    if (value) element.textContent = value;
  });

  document.querySelectorAll("[data-i18n-html]").forEach((element) => {
    const value = getTranslation(element.dataset.i18nHtml, language);
    if (value) element.innerHTML = value;
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
    const value = getTranslation(element.dataset.i18nPlaceholder, language);
    if (value) element.setAttribute("placeholder", value);
  });

  localStorage.setItem("green-heaven-language", language);
};

const currentLanguage = () => languageSelect?.value || "en";

const updateHeader = () => {
  header?.classList.toggle("is-scrolled", window.scrollY > 32);
};

updateHeader();
window.addEventListener("scroll", updateHeader, { passive: true });

if (toggle && nav) {
  toggle.addEventListener("click", () => {
    const open = nav.classList.toggle("is-open");
    header?.classList.toggle("menu-active", open);
    document.body.classList.toggle("nav-open", open);
    toggle.setAttribute("aria-expanded", String(open));
  });

  nav.querySelectorAll("a").forEach((link) => {
    link.addEventListener("click", () => {
      nav.classList.remove("is-open");
      header?.classList.remove("menu-active");
      document.body.classList.remove("nav-open");
      toggle.setAttribute("aria-expanded", "false");
    });
  });
}

languageSelect?.addEventListener("change", () => {
  applyLanguage(currentLanguage());
});

const savedLanguage = localStorage.getItem("green-heaven-language");
if (languageSelect && savedLanguage && translations[savedLanguage]) {
  languageSelect.value = savedLanguage;
}
applyLanguage(currentLanguage());

const openWhatsApp = (message) => {
  window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`, "_blank", "noopener");
};

const selectedText = (formElement, name) => {
  const field = formElement.elements[name];
  return field?.options?.[field.selectedIndex]?.text || field?.value || "";
};

const formatBookingMessage = ({ name, phone, checkin, checkout, persons, packageName, airport, message, source }) => {
  return [
    "Hello Green Heaven Eco Resort,",
    "",
    "I would like to make a booking enquiry from the website.",
    "",
    `Name: ${name || "Not provided"}`,
    `WhatsApp / Phone: ${phone || "Not provided"}`,
    `Check-in Date: ${checkin || "Not provided"}`,
    `Check-out Date: ${checkout || "Not provided"}`,
    `Guests: ${persons || "Not provided"}`,
    `Package: ${packageName || "Not provided"}`,
    `Airport pickup: ${airport || "Not provided"}`,
    `Special request: ${message || "None"}`,
    "",
    `Source: ${source}`
  ].join("\n");
};

bookingForm?.addEventListener("submit", (event) => {
  event.preventDefault();
  const data = new FormData(bookingForm);
  const language = currentLanguage();
  const button = bookingForm.querySelector("button");
  const message = formatBookingMessage({
    name: data.get("name"),
    phone: data.get("phone"),
    checkin: data.get("checkin"),
    checkout: data.get("checkout"),
    persons: data.get("persons"),
    packageName: selectedText(bookingForm, "package"),
    airport: selectedText(bookingForm, "airport"),
    message: "Please confirm availability, price and booking details.",
    source: "Hero booking form"
  });

  if (button) button.textContent = getTranslation("status.button", language);
  openWhatsApp(message);
  window.setTimeout(() => {
    if (button) button.textContent = getTranslation("form.bookWhatsapp", language);
  }, 1600);
});

form?.addEventListener("submit", (event) => {
  event.preventDefault();
  const data = new FormData(form);
  const language = currentLanguage();
  const button = form.querySelector("button");
  const message = formatBookingMessage({
    name: data.get("name"),
    phone: data.get("phone"),
    checkin: data.get("checkin"),
    checkout: data.get("checkout"),
    persons: data.get("persons"),
    packageName: selectedText(form, "package"),
    airport: selectedText(form, "airport"),
    message: data.get("message"),
    source: "Contact enquiry form"
  });

  if (status) status.textContent = getTranslation("status.opening", language);
  if (button) button.textContent = getTranslation("status.button", language);
  openWhatsApp(message);
  window.setTimeout(() => {
    if (button) button.textContent = getTranslation("form.sendWhatsapp", language);
  }, 1600);
});

// Interactive package selection from package buttons
document.querySelectorAll('a[href="#booking"][data-package]').forEach((link) => {
  link.addEventListener("click", () => {
    const packageName = link.getAttribute("data-package");
    if (packageName) {
      document.querySelectorAll('select[name="package"]').forEach((select) => {
        select.value = packageName;
      });
    }
  });
});
